# Independent settings for the planner's costmap
global_costmap:

  global_frame    : $(arg robot_namespace)/map
  robot_base_frame: $(arg robot_namespace)/base_footprint

  update_frequency : 10.0
  publish_frequency: 1.0

  track_unknown_space: true
  unknown_cost_value : 255

  footprint: [[ 0.35, 0.24], [-0.35, 0.24], [-0.35, -0.24], [ 0.35, -0.24]]

  #plugins are loaded in a separate file

  static_layer:
    enabled  : true
    map_topic: map

  front_obstacle_laser_layer:
    enabled: true
    observation_sources: base_scan
    combination_method: 0 # can erase static layer

    base_scan:
      sensor_frame: $(arg robot_namespace)/base_front_laser_link
      data_type: LaserScan
      topic: scan_front_raw
      expected_update_rate: 0.3
      observation_persistence: 0.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 4.0
      obstacle_range: 3.0

  rear_obstacle_laser_layer:
    enabled: true
    observation_sources: base_scan
    combination_method: 0 # can erase static layer

    base_scan:
      sensor_frame: $(arg robot_namespace)/base_rear_laser_link
      data_type: LaserScan
      topic: scan_rear_raw
      expected_update_rate: 0.3
      observation_persistence: 0.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 4.0
      obstacle_range: 3.0

  inflation_layer:
    enabled            : true
    inflation_radius   : 0.55
    cost_scaling_factor: 25.0
