# Independent settings for the local costmap
local_costmap:

  global_frame    : $(arg robot_namespace)/odom
  robot_base_frame: $(arg robot_namespace)/base_footprint

  update_frequency : 10.0
  publish_frequency: 1.0

  rolling_window: true
  width         : 4.0
  height        : 4.0
  resolution    : 0.025

  robot_radius: 0.275

  #plugins are loaded on a separate file

  obstacle_laser_layer:
    enabled: true
    observation_sources: base_scan
    combination_method: 0 # can erase static layer

    base_scan:
      sensor_frame: $(arg robot_namespace)/base_laser_link
      data_type: LaserScan
      topic: scan
      expected_update_rate: 0.3
      observation_persistence: 0.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 4.0
      obstacle_range: 3.0

  obstacle_sonar_layer:
    enabled: false
    ns: "/$(arg robot_namespace)"
    topics: ["sonar_base"]
    no_readings_timeout: 0.0
    clear_threshold: 0.20
    mark_threshold: 0.80
    clear_on_max_reading: true

  inflation_layer:
    enabled            : true
    inflation_radius   : 0.1
    cost_scaling_factor: 5.0
